name: INFRA WORKFLOW AKS #optional pipeline name

on:  #workflow kab chalega
  push:
    branches:
    - main
    - feature/*
permissions:  #OIDC m permission dena padta h
  id-token: write
  contents: read
  
jobs:
  scanning_tool:
    name: scanning tool
    runs-on: ubuntu-latest # y github hosted m run hoga
    steps:
    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v6.2.1  
  
    
  terraform_init_plan:  #job id
    name: terraform init plan #job name
    runs-on: self-hosted #runner and tag dena padta h
    
    
    steps:
    - name: Checkout
      uses: actions/checkout@v6.0.2


    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        # ClientId of the Azure Service principal created.
        client-id: 24173b11-ec1b-4072-813a-0aa8e3e81acf
        # TenantId of the Azure Service principal created.
        tenant-id: 66c291b4-1789-4bcb-9817-6b0339a238bc
        subscription-id: cef3b1fa-2c9d-4212-843c-0107fc35ca77
    
    - name: terraform fmt
      run: terraform fmt
      working-directory: env/dev
      
    - name: terraforminit
      run: terraform init
      working-directory: env/dev
      
    - name: terraform plan
      run: terraform plan
      working-directory: env/dev

      
  terraform_init_apply:  #job id
    name: terraform appply plan #job name
    runs-on: self-hosted #runner and tag dena padta h
    needs: terraform_init_plan # y depends_on ki trah h
    environment: dev # y approval k liye h
    
    steps:
    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        client-id: 24173b11-ec1b-4072-813a-0aa8e3e81acf
        tenant-id: 66c291b4-1789-4bcb-9817-6b0339a238bc
        subscription-id: cef3b1fa-2c9d-4212-843c-0107fc35ca77
    
    - name: terraform init
      run: terraform init
      working-directory: env/dev
      
    - name: terraform apply
      if: github.ref == 'refs/heads/main' # sirf main s chlega apply y condition h 
      run: terraform apply
      working-directory: env/dev
