name: new code AKS #optional 

on:  #workflow kab chalega
  push:
    branches:
    - main
    - feature/*

jobs:
  terraforminit:  #job id
    name: terraform initss #job name
    runs-on: self-hosted #runner
    steps:
    - name: echo command
      run: echo "sam"
