name: new code AKS

on:
  push:
    branches:
    - main
    - feature/*

jobs:
  terraforminit:
    name: terraform initss
    runs-on: LAPTOP-4TFFDUNE
    steps:
    - name: echo command
      run: echo "sam"
